# Generated by Django 5.2.5 on 2025-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=25)),
                ('telegram', models.CharField(max_length=25)),
                ('instagram', models.CharField(max_length=25)),
            ],
        ),
    ]
