# Generated by Django 5.2.5 on 2025-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(max_length=40),
        ),
    ]
