# Generated by Django 5.2.5 on 2025-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_app', '0002_alter_footer_instagram_alter_footer_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
